/**
 * Build-time script: embed vendor OAuth credentials into the release bundle.
 * Customers never receive vendor-google-oauth.json — only the baked module.
 *
 * Usage: node scripts/bake-oauth.js
 * Env:   RELEASE_PORT (default 3000), GOOGLE_OAUTH_CREDENTIALS_FILE
 */

const fs   = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PORT = process.env.RELEASE_PORT || '3000';
const OUT  = path.join(ROOT, 'src', 'google-auth', 'baked-credentials.js');

const CANDIDATES = [
  process.env.GOOGLE_OAUTH_CREDENTIALS_FILE,
  'vendor-google-oauth.json',
  'oauth-spike.credentials.json',
].filter(Boolean);

function findCredentials() {
  for (const name of CANDIDATES) {
    const credPath = path.isAbsolute(name) ? name : path.join(ROOT, name);
    if (fs.existsSync(credPath)) return credPath;
  }
  return null;
}

function main() {
  const credPath = findCredentials();
  if (!credPath) {
    console.error('[bake-oauth] No vendor credentials file found.');
    console.error('  Copy vendor-google-oauth.example.json → vendor-google-oauth.json');
    process.exit(1);
  }

  const raw = JSON.parse(fs.readFileSync(credPath, 'utf8'));
  const web = raw.web || raw.installed || raw;
  const clientId     = web.client_id     || process.env.GOOGLE_OAUTH_CLIENT_ID     || '';
  const clientSecret = web.client_secret || process.env.GOOGLE_OAUTH_CLIENT_SECRET || '';

  if (!clientId || !clientSecret) {
    console.error('[bake-oauth] client_id and client_secret are required.');
    process.exit(1);
  }

  const redirectUri = `http://127.0.0.1:${PORT}/api/google/auth/callback`;

  const content = `/**
 * AUTO-GENERATED by scripts/bake-oauth.js — do not edit.
 * OAuth credentials are embedded at build time for the Windows release.
 */
module.exports = {
  clientId:     ${JSON.stringify(clientId)},
  clientSecret: ${JSON.stringify(clientSecret)},
  redirectUri:  ${JSON.stringify(redirectUri)},
};
`;

  fs.writeFileSync(OUT, content, 'utf8');
  console.log(`[bake-oauth] Wrote ${path.relative(ROOT, OUT)}`);
  console.log(`[bake-oauth] Redirect URI: ${redirectUri}`);
  console.log('[bake-oauth] Add this URI in Google Cloud → OAuth client → Authorized redirect URIs');
}

main();
